### ISSUE TITLE
Drupal Error Handler takes 5 Arguments

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar-php#388] opened 2018-07-18 21:38 UTC
While using Drupal 8.4 under PHP 7.1, a user is being hit by an 
```
ArgumentCountError: Too few arguments to function drush_error_handler(), 4 passed and 5 expected
```

![image](https://user-images.githubusercontent.com/10730200/42909226-3949715e-8a98-11e8-806d-b6719f8aab2d.png)

Do we have any plans to accommodate this?

**Comment by ArturMoczulski** [comment] 2018-10-23 18:14
@jessewgibbs why was this closed?

**Comment by jessewgibbs** [comment] 2018-10-23 18:15
@ArturMoczulski must have been by accident as I didn't leave a comment.  Sorry about that!

**Comment by ArturMoczulski** [comment] 2018-10-25 11:29
@ajtran I've tried but I'm unable to reproduce this problem. Can you reach out to the user and ask where and how is the initialization of Rollbar in Drupal being done in this case?

**Comment by penance316** [comment] 2018-10-29 12:06
Hi thanks for retesting this.

I have just tried to recreate in my project and cannot reproduce the issue currently either.

I am happy to close this issue and appreciate your time with this.

**Closed** 2018-10-31 16:00 UTC
Labels: question
