### ISSUE TITLE
Info in trace_chain is Not Scrubbed

### ISSUE THREAD

**Issue by adrian-enspired** [rollbar/rollbar-php#347] opened 2018-04-16 17:33 UTC
Rollbar payloads include sensitive information in `body.trace_chain..args` which is not being "scrubbed."  For example, the raw JSON includes:
```json
{
  "body": {
    "trace_chain": [
      . . .
      {
        "frames": [
          . . .
          {
            "method": "{redacted}\\Db::connect", 
            "args": [
              {
                "username": "{redacted}", 
                "hostname": "{redacted}", 
                "database": "{redacted}", 
                "charset": null, 
                "dsn": "{redacted}", 
                "slaves": [], 
                "collation": null, 
                "password": "{redacted}", 
                "type": "mysql", 
                "port": null
```
Note that fields named "password" are supposedly scrubbed by default.  I've redacted the sensitive info here, but it **is** present in clear text in the issue occurrence.

My understanding from reading rollbar docs was that the "scrub_fields" config value applied to `$_POST` and `$_SESSION`, but rollbar support tells me that it should be "scrubbing" these values from the trace as well.

Two questions:

1) Does "scrub_fields" apply to values in `body.trace_chain`?  If so, why are these values not being scrubbed?

2) If not, is there any config setting or rollbar-php method which would allow me to scrub these values manually?

**Comment by rivkahstandig3636** [comment] 2018-04-18 14:46
Thanks for the bug report! We'll take a look into this.

**Comment by adrian-enspired** [comment] 2018-04-25 14:11
Any update on this issue?  Thanks for your time!

**Comment by rivkahstandig3636** [comment] 2018-04-25 16:15
Hi @adrian-enspired, unfortunately not yet. We'll update the issue here when there is an update. Sorry for the delay!

**Comment by adrian-enspired** [comment] 2018-05-04 15:11
Checking in again.

I understand that there may not be a solution yet, but it would be very helpful to have confirmation of what/if the problem is.

**→ Is "scrub_fields" _meant_ to apply to values to `body.trace_chain`, or no?**

**Comment by ArturMoczulski** [comment] 2018-05-04 16:57
@adrian-enspired `scrub_fields` IS meant to be applied to values in `body.trace_chain`. If it doesn't then it's a bug in our code. As soon as I get to resolving this issue, I will try to reproduce your situation and find out where the problem is.

**Comment by Hoten** [comment] 2018-06-21 06:22
It's because the Scrubber ignore objects. It only scrubs strings and arrays. The frames are instances of the Rollbar\Payload\Frame class.

I was able to extend the Scrubber and scrub the frames like this:
```
public function internalScrub(&$data, $fields, $replacement, $path)
    {
        // original scrubber does not scrub trace args
        if ($data instanceof \Rollbar\Payload\Frame) {
            if ($data->getArgs()) {
                $args = $data->getArgs();
                $args = $this->scrubArray($args, $fields, $replacement, $path);
                $data->setArgs($args);
            }
            return $data;
        } else {
            return parent::internalScrub($data, $fields, $replacement, $path);
        }
    }
```

I can open a PR for this, just say the word. Also, if you want this behind a config value, let me know.

**Comment by Hoten** [comment] 2018-06-21 16:54
The above only scrubs args that happen to be arrays ... if an arg is called `$password` and is the first parameter, it won't scrub that. Any ideas there?

**Comment by ArturMoczulski** [comment] 2018-08-04 08:52
@adrian-enspired I believe this problem has been resolved in `master`. Can you please, check if your payloads get scrubbed as expected when using the latest `mater` code? I just tested and I'm not able to reproduce the issue.

**Closed by ArturMoczulski** 2018-08-04 08:52 UTC
Labels: bug
