### ISSUE TITLE
Rollbar creates hundreds of thousands of rollbar-relay files on error

### ISSUE THREAD

**Issue by ahfeel** [rollbar/rollbar-php#496] opened 2020-08-18 15:09 UTC
Hello,

It seems Rollbar-php has edge cases when working with the agent handler where it can creates unlimited amounts of rollbar-relay files and ending up filling up the hard drive.

Is there a way to configure the PHP SDK or the AGENT to avoid this ?

Best,
Jérémie

**Comment by bishopb** [comment] 2020-12-03 04:34
Thanks for writing in! Looking at [the code that creates the relay files](https://github.com/rollbar/rollbar-php/blob/master/src/Senders/AgentSender.php#L63), I can definitely see how this could create lots of files. One way would be if your code was spawning many different processes and each was getting its own agent file. Another might be if the relay agent files live on a networked file system, where the fopen times out but the kernel-space driver creates the file anyway (I've seen this on s3fs).

A few details would help diagnose this further:

1. What OS, OS version, PHP version, and/or web server and version did you observe this on?
2. What type of filesystem were the relay log files held on?
3. Could you provide an example of the files created (eg, the output of `ls -l`)
4. Is this reproducible? If so, how?

In addition, I think it would be helpful to provide better diagnostics in the event that `AgentSender::loadAgentFile` fails: the code that follows it does not expect it to fail and now it's assumed it always works (which may not be the case, of course: full filesystems, networked filesystems, etc.).

**Comment by danielmorell** [comment] 2022-05-23 22:19
Hi @ahfeel, I am going to close this issue for now as we are unable to diagnose the cause it without a little more context.

**Closed by danielmorell** 2022-05-23 22:19 UTC
Labels: Type: Question, Status: 1 - Discussion, Rank: 4 - Low
