### ISSUE TITLE
Maximum execution time of 30 seconds in DataBuilder.php

### ISSUE THREAD

**Issue by sebestenyb** [rollbar/rollbar-php#204] opened 2017-06-15 07:11 UTC
Hi there

the error log of our site is full of these error messages:

```
[2017-06-15 18:54:28] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Maximum execution time of 30 seconds exceeded in /var/www/www.example.com/vendor/rollbar/rollbar/src/DataBuilder.php:409
Stack trace:
#0 {main}
```

I'd appreciate any help, thanks!

Cheers, Sebi

**Comment by coryvirok** [comment] 2017-06-15 19:59
Yikes! Thanks for bringing this to our attention!

**Comment by sebestenyb** [comment] 2017-06-15 20:01
I'm sorry, couldn't really track down what's going on, the stack trace is only that one line you see

**Comment by rokob** [comment] 2017-06-15 20:03
What version are you using? There used to be an infinite loop there.

**Comment by sebestenyb** [comment] 2017-06-15 20:09
```
            "name": "rollbar/rollbar-laravel",
            "version": "v2.0.0",
```

```
            "name": "rollbar/rollbar",
            "version": "v1.0.1",
```

**Comment by rokob** [comment] 2017-06-15 20:14
It is weird that it is pointing to Line 409, which is the point where the code currently lives that used to have a loop. The fix was https://github.com/rollbar/rollbar-php/pull/158 which is in v1.1.0 and later. The bug was definitely in v1.0.1, but it was on a different line. So I'm not exactly sure what is happening, but I strongly suspect the line number in the stack trace is just wrong and the issue is the one that has since been fixed.

**Comment by coryvirok** [comment] 2017-06-15 20:17
Maybe the process hasn't been restarted since the rollbar library was updated?

**Comment by sebestenyb** [comment] 2017-06-15 20:17
```
        $source = str_replace(array("\n", "\t", "\r"), '', $source);
        $total = count($source);
        $line = $line - 1;
        $frame->setCode($source[$line]);
```

**Comment by sebestenyb** [comment] 2017-06-15 20:19
https://github.com/rollbar/rollbar-php/blob/v1.0.1/src/DataBuilder.php#L409

**Comment by rokob** [comment] 2017-06-15 20:28
Yeah that code doesn't make sense to me that it could ever really take more than 30 seconds. On the other hand, https://github.com/rollbar/rollbar-php/blob/v1.0.1/src/DataBuilder.php#L342 can for sure result in an infinite loop. But if we start from the presumption that L409 in v1.0.1 actually can take a long time, let me look into what might be happening there.

**Comment by rokob** [comment] 2017-06-15 20:40
Okay so potentially this has to do with different line endings, I still am not sure because I wouldn't expect a timeout but a different error, but it could be related to https://github.com/rollbar/rollbar-php/pull/185

**Comment by sebestenyb** [comment] 2017-06-15 21:33
I realised that for this project we actually ran out of our quota on Rollbar - could it be an issue?

**Comment by rokob** [comment] 2017-06-19 21:09
The quota should not matter, it should just return a response from the server saying as much and finish quickly.

**Comment by sebestenyb** [comment] 2017-06-19 21:48
I've double checked, and I do restart the queue workers on deploy, so it's 100% that a package update would use the new libraries.

But as far as I know we don't even have queued jobs here, only regular web requests.

**Comment by ArturMoczulski** [comment] 2017-08-11 03:42
@sebestenyb Is there an update on this? Are you still experiencing problems?

**Comment by rokob** [comment] 2017-08-19 01:13
Closing, please re-open or open a new issue if this is still a problem.

**Closed by rokob** 2017-08-19 01:13 UTC
Labels: bug
