### ISSUE TITLE
Typo in EncodedPayload->decreaseSize

### ISSUE THREAD

**Issue by Ramapitecus** [rollbar/rollbar-php#426] opened 2018-12-08 14:44 UTC
https://github.com/rollbar/rollbar-php/blob/c2f8be87983ecdd3c46ceb3c459de02376af4707/src/Payload/EncodedPayload.php#L26

`$this->size =- $amount`

**Comment by jessewgibbs** [comment] 2018-12-10 18:57
@ramapitecus thanks for bringing this to our attention (as well as #427 and #428).

@ArturMoczulski can you take a look when you get a chance?

**Comment by ArturMoczulski** [comment] 2018-12-17 03:04
I'm not sure I understand what the problem is here

**Comment by Ramapitecus** [comment] 2018-12-17 10:22
I'm sorry I wasn't clear. The method is called `decreaseSize` so I assume that if `$this->size` is 10, and you call `$obj->decreaseSize(2)` you'ld want `$this->size === 8` but there is a typo there, the `=-` is flipped. And `$this->size === -2` after that call.

**Comment by ArturMoczulski** [comment] 2018-12-20 19:52
Fixed in `master`. Will be included in the next release.

**Closed by ArturMoczulski** 2018-12-20 19:52 UTC

**Comment by ArturMoczulski** [comment] 2019-01-02 14:35
Released in `v1.7.3`
