### ISSUE TITLE
Performance Benchmark for Rollbar:init()

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar-php#404] opened 2018-08-29 19:31 UTC
internal: https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/813334/conversations/18056584141

user: We just did some benchmarking in our production environment. With the 0.18.2 rollbar-php library, Rollbar::init() is a sub-millisecond operation. In 1.6.2, it takes an average of ~150 milliseconds, with 99th percentile ~270 milliseconds.

Further measurement and documentation of this as well as performant work if necessary would be a great enhancement to the SDK

**Comment by ArturMoczulski** [comment] 2018-08-30 23:14
Thanks @joshrai those are great insights. I'm putting the SDK under a magnifying glass to find the culprits.

**Comment by ArturMoczulski** [comment] 2018-08-31 07:31
@joshrai if you want an immediate boost in performance, setting up `allow_exec` to `false` will boost the SDK init by 30% right away. In the above PR I made that a default in the library.

There is one more performance spike I'm looking at before I merge those changes. Should be coming along in the next couple of days @jessewgibbs

**Comment by joshrai** [comment] 2018-08-31 19:05
Thanks, @ArturMoczulski -- good to know. I just tried that and am seeing similar results. Just to confirm, doing this means that if we want to continue including our Git branch in log events, we should explicitly set a `branch` entry?

I should also mention, our app is very latency-sensitive. We can't easily afford more than ~5 milliseconds for this call. If there's any other info I can provide to help winnow this down, let me know.

**Comment by joshrai** [comment] 2018-08-31 23:33
I'm getting more confident that the remaining cost, at least in my env, has something to do with object construction overhead outside the source code itself, and somehow specifically for the `Config` class. I added some benchmarking code from just before calling `new Config()`:

https://github.com/rollbar/rollbar-php/blob/1deec89b870899d12794bb75377ca60359f18723/src/RollbarLogger.php#L22

to the first line of the `Config` constructor itself -- before this:

https://github.com/rollbar/rollbar-php/blob/1deec89b870899d12794bb75377ca60359f18723/src/Config.php#L149

and that interval is tending to account for ~90% of the time taken by `Rollbar::init()`. In fact, as it happens, the remaining time seems to be in the neighborhood of 5 msec, so if we could figure this bit out, it might get us home.

This seems like something that could be specific to the particular HHVM (or PHP) implementation, but I think it'll take some more advanced profiling than what I've been doing to learn more.

**Comment by ArturMoczulski** [comment] 2018-09-01 00:30
@joshrai Yes! Here is a PR I opened with the improvements I'm working on: https://github.com/rollbar/rollbar-php/pull/406

So far I was able to shave off init execution to about 3.5 msec.

**Comment by ArturMoczulski** [comment] 2018-09-06 21:40
@joshrai I merged PR 406 with performance improvements and released under `v1.6.3`: https://github.com/rollbar/rollbar-php/releases/tag/v1.6.3

I see drastic improvements in PHP 7.2 but my HHVM setup is being funny. Can you help me and test with your setup?

**Comment by ArturMoczulski** [comment] 2018-09-06 21:55
@joshrai another suggestion I have is to set `optimize-autoloader` to true in your composer if you are not doing that already. This will switch you from dynamic autoloading lookups to a static class map generated at `composer update` which is preferred for production environments.

**Comment by joshrai** [comment] 2018-09-07 01:43
Awesome, thanks, @ArturMoczulski -- I'll try this out as soon as I can!

And thanks for the tip. We do use the `optimize-autoloader` option, although we also use an HHVM-oriented Composer plugin, https://github.com/hhvm/hhvm-autoload. I'm not enough of an expert on this subject to know how these two things interact, or if there's some more optimization we could do with our hhvm-autoload settings, but there are others on my team who have spent time tuning it.

**Comment by ArturMoczulski** [comment] 2018-09-08 02:26
Interesting. I'm going to do more profiling on HHVM. The improvements I posted were measured on vanilla PHP 7.2. @joshrai thanks for your efforts to help with this.

**Comment by ArturMoczulski** [comment] 2018-09-08 04:37
@joshrai did some poking around with HHVM.

I turned off JIT compilation with `hhvm -v Eval.Jit=0` to skip the JIT warm up and arrived at ~12msec execution time compared to the previous 500msec+.

Can you run a test with JIT turned off? Not sure how exactly you are using the SDK, but it might make sense to configure a warm-up threshold when it comes to JIT.

**Comment by coryvirok** [comment] 2018-09-13 19:02
Hey all. I'm not a PHP performance expert but if the issue is showing up in JIT'd code, it's likely slow because of all of the method calls in `updateConfig()` I think we can try refactoring the Config constructor to make less method calls. I'd guess that most of those `{internal}` calls are method pointer lookups and type lookups.

Some other useful info: https://hhvm.com/blog/713/hhvm-optimization-tips

**Comment by joshrai** [comment] 2018-09-13 21:13
Yes, I wouldn't be too concerned about a moderately high number of ordinary method calls, but it's possible that the dynamic method calls, like the ones triggering `Defaults::__call()`, are causing more overhead in our HHVM setup than in PHP.

I don't have a complete picture to give you at this point regarding JIT implications, because it's a heavy lift for us to test this in a safe, controlled manner in a prod (or very prod-like) environment, which does use the JIT; so far we've only tried 1.6.3 in dev, where the JIT is disabled and we don't use repo authoritative mode.

**Comment by coryvirok** [comment] 2018-09-13 23:28
Hrrmmm, ya. Can we just refactor this type of code like so?
```php
        $this->verbosity = \Rollbar\Defaults::get()->verbosity();
```
to
```php
        $this->verbosity = \Rollbar\Defaults['verbosity'];
```

And have the Defaults class just be a a simple mapping object instead of a class with (magic) methods?

**Comment by ArturMoczulski** [comment] 2018-09-13 23:39
@joshrai thanks for the absolutely amazing insights and shots of your xhprof profiling. that's very helpeful.

I'm refactoring Defaults class today as per yours and @coryvirok suggestions as well as looking for further ways to optimize for HHVM. I'll let you know how refactoring magic method calls to mapping object affects the wall time

**Comment by joshrai** [comment] 2018-09-22 05:55
I think I might have stumbled onto something promising. I'm going to need to get more eyes on this from my colleagues, but long story short, I'm suspecting that the performance problem I've been seeing is a combination of the way we configure the `hhvm-autoload` Composer plugin and the way it handles an undefined (though properly checked) constant, as in `Config.php`:

https://github.com/rollbar/rollbar-php/blob/149590adc3bd5ed1188c48f8159f257aa1bf2d19/src/Config.php#L7-L12

In my dev environment using Rollbar 1.6.3, when I either make a particular change to our `hhvm-autoload` config or ensure that I define the `ROLLBAR_INCLUDED_ERRNO_BITMASK` constant before calling `Rollbar::init()`, it looks like that call goes back down to sub-millisecond time! I even got my dev env to use repo authoritative mode, to be a little more like our prod setup.

We've been including the following in our `hh_autoload.json` to configure `hhvm-autoload`:

```
{
  "autoloadFilesBehavior": "exec",
  "devFailureHandler": "Facebook\\AutoloadMap\\HHClientFallbackHandler",
   ...
}
```

I finally realized that xhprof was showing that that fallback handler was taking up a lot of time during Rollbar `Config` construction (it was buried under a call marked `{internal}`). I put in a custom subclass for `devFailureHandler` so I could log the names of the symbols that were not getting resolved, and saw that `ROLLBAR_INCLUDED_ERRNO_BITMASK` came up. When I defined that constant in my code before calling `Rollbar::init()`, that handler didn't get called, and the performance became acceptable again.

Similarly, when I changed `devFailureHandler` to be unset, the performance was fine -- even if I didn't first define `ROLLBAR_INCLUDED_ERRNO_BITMASK`. I don't quite understand what the behavior of this plugin is when the failure handler is not set (which is the default and seems to be considered acceptable), but it seems to work.

One thing that's still unclear to me is what's going on in production. It's possible that the performance trouble we had with 1.6.2 was all because of the git exec problem, but I want to triple-check that our `hhvm-autoload` setup in prod does not involve a failure handler. I'll try to get an answer next week.

I'm also curious why we aren't leaving `autoloadFilesBehavior` to the default, "preferred" setting. From the docs, it seems vaguely like this could be doing something expensive when it can't resolve a name. But there's probably a good reason why we set it that way, so I'm not counting on being able to change that.

**Comment by joshrai** [comment] 2018-09-22 06:49
As an aside, we have a number of places in our own code base where we say things like `if (!defined('FOO')) define('FOO', false);`, and they run perfectly fast and don't seem to trigger the autoload failure handler on my dev server. I'm not sure what the difference is, but maybe it's because in our case it's explicitly declared to be Hack code rather than PHP (the files they're in start with `<?hh` rather than `<?php`).

**Comment by joshrai** [comment] 2018-09-22 18:05
I confirmed with the help of a colleague that we do not have an autoload fallback handler running in prod, so I'm a little more hopeful that 1.6.3 would perform fine in our production environment. It's harder than it should be for us to test changes like this in a safe and controlled way in prod, but I'll work on it -- hope we'll be able to give it a try soon.

**Comment by ArturMoczulski** [comment] 2018-09-28 16:43
Hey @joshrai 

I've been experimenting a lot with the SDK initialization after our call. Unfortunately, I don't see the same behavior in regards to the fallback handler. Defining the `ROLLBAR_INCLUDED_ERRNO_BITMASK` makes only an insignificant difference in my measurements. I'd love to know more about what you found out.

I include the screenshots of my benchmarks with a progression of improvement as I introduced different optimizations:

<img width="1001" alt="screen shot 2018-09-28 at 6 41 46 pm" src="https://user-images.githubusercontent.com/2106631/46221639-3478d680-c34e-11e8-8def-601a7b3e606c.png">

I added quite a bit of changes to the code since `v1.6.3` now so I'm going to release those now as `v.1.6.4`. I believe it would be excellent if you could try to pull in `v1.6.4` into your environment and see how your codebase performs.

**Comment by joshrai** [comment] 2018-10-10 00:45
Hi @ArturMoczulski , I finally was able to get v1.6.3 into our production environment, and it looks great! Based on an hour of sampling, the median time for calling `Rollbar::init()` is about 200 microseconds, and 99th percentile is under 350 microseconds.

Thank you, and great work!

**Comment by jessewgibbs** [comment] 2018-10-10 15:52
@ArturMoczulski sounds like we've got the performance to a good place.  Can we go ahead and close this issue?

**Comment by ArturMoczulski** [comment] 2018-10-10 16:13
Let's check with @joshrai how are their performance is doing now? @joshrai did you have a chance to run more tests with latest releases?

**Comment by joshrai** [comment] 2018-10-10 16:17
Yes, see https://github.com/rollbar/rollbar-php/issues/404#issuecomment-428400026 -- looking great! I'd say this can be closed. Thank you!

**Closed** 2018-10-11 15:54 UTC
