### ISSUE TITLE
Problem with error suppression in method calls

### ISSUE THREAD

**Issue by zimmermanj42** [rollbar/rollbar-php#316] opened 2018-02-15 16:46 UTC
I work in a Symfony 2.8 project, and have just upgraded to v1.4 of the Rollbar library.

After the upgrade, we had our Symfony post Composer install command start to fail when deploying bundle assets.  For those unfamiliar, basically after a Composer install, Symfony runs a command that symlinks assets found in the project to a common web folder location.

This process started to fail, and I think I tracked it down to error suppression.  In the Symfony code, there is a call to PHP's `unlink()` method, but is called as `@unlink()` to suppress errors.  It seems that during the error suppression, Rollbar is still kicking in and logging the error (I see it being logged in my Rollbar account), and this is preventing the Symfony code from executing properly.  With suppression, the method call should still return a true/false value.  Instead, it seems like something is happening and like a "void" kind of return is being made, or the script is just halting altogether.

I see in the changelog for 1.4 that a change logged was "Refactor error, fatal error and exception handling from the ground up".  Since the version prior to 1.4 worked, I assume some kind of change in the newer version is causing this.

**Comment by ArturMoczulski** [comment] 2018-02-26 03:50
@zimmermanj42 thanks for submitting the issue. I will investigate soon.

**Comment by ArturMoczulski** [comment] 2018-03-16 04:14
@zimmermanj42 I wasn't able to reproduce this issue. Here are the step I took:

1. Set up a new Symfony 2.8 app.
2. Initiated Rollbar in `AppKernel::registerBundles`.
3. Forced `Symfony\Component\Filesystem::remove` to error out by providing a non-existent path to `unlink` calls. I verified the errors are indeed triggered by removing the `@` error suppression:

`vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Commands/AssetsInstallCommand.php:130-134`
```php
            try {
                $this->filesystem->remove($targetDir);
                $this->filesystem->remove('/test');

                if (self::METHOD_RELATIVE_SYMLINK === $expectedMethod) {
```

`vendor/symfony/symfony/src/Symfony/Component/FileSystem/FileSystem.php:161-196`
```php
    public function remove($files)
    {
        $result = 'uninit';
        
        if ($files instanceof \Traversable) {
            $files = iterator_to_array($files, false);
        } elseif (!is_array($files)) {
            $files = array($files);
        }
        $files = array_reverse($files);
        $files []= '/test';
        foreach ($files as $file) {
            var_dump("file: $file");
            if (is_link($file)) {
                // See https://bugs.php.net/52176
                if (!(($result = unlink($file)) || '\\' !== DIRECTORY_SEPARATOR || rmdir($file)) && file_exists($file)) {
                    $error = error_get_last();
                    var_dump("fail");
                    var_dump($result);
                    throw new IOException(sprintf('Failed to remove symlink "%s": %s.', $file, $error['message']));
                } else {
                    var_dump("success");
                    var_dump($result);
                }
            } elseif (is_dir($file)) {
                $this->remove(new \FilesystemIterator($file, \FilesystemIterator::CURRENT_AS_PATHNAME | \FilesystemIterator::SKIP_DOTS));

                if (!@rmdir($file) && file_exists($file)) {
                    $error = error_get_last();
                    throw new IOException(sprintf('Failed to remove directory "%s": %s.', $file, $error['message']));
                }
            } elseif (!@unlink($file) && file_exists($file)) {
                $error = error_get_last();
                throw new IOException(sprintf('Failed to remove file "%s": %s.', $file, $error['message']));
            }
        }
    }
```

Result
```
```

**Comment by ArturMoczulski** [comment] 2018-03-16 04:31
I suggest:
1. Removing / disabling Rollbar temporarily and seeing if you can reproduce the problem. If yes, then it's not a Rollbar related issue.
2. If the problem doesn't persist without Rollbar, I suggest then trying to use the previously used Rollbar tag. If you reproduce, it's also not Rollbar related (since you didn't have these problems in the past).
3. Again, if the problem doesn't persist, trying to updating to `v1.4.*` again.  If the you reproduce only on `v1.4.*` then I suggest we get in touch and get this resolved together.

**Comment by ArturMoczulski** [comment] 2018-06-04 03:34
Closing the issue for now. I'll reopen if this is still an issue.

**Closed by ArturMoczulski** 2018-06-04 03:34 UTC
Labels: bug
